### PR TITLE
Fluent API; OAuth further implementation; removing req on config()

### PR DESCRIPTION
**Pull request by igorsantos07**
- Removing hard requirement on `config()`
- setting `setAccount()` as fluent as well
- and _actually_ implementing the rest of OAuth2 support (returning Authorize URL for redirect and retrieving the final token)

### CODE REVIEW

**Comment by ahuggins** [comment]
Hey @igorsantos07, thanks for the PR's. Just want to make sure you are submitting to the correct repo. This is a fork of the https://github.com/gridonic/hapi repo, but we added support for connecting via oAuth, which I think the original did not have.

If that's correct, then we will review and merge when we get a chance. Quick glance looks good, but just want to review further and make sure you are on the right repo. Thanks!

**Comment by igorsantos07** [comment]
Yeah, I'm actually _finishing_ the oAuth implementation. This repo got it done but it seems halfway...
As I'm using it on a new project, I'm adding a bunch of small improvements to the code to get it in working state.

**Comment by ahuggins** [comment]
You are right about it not being complete, the oAuth implementation was done pretty quickly for a specific use case we had at the time. Served our purpose at the moment and we've been focused on other things for a while. (you know how that goes.)

I don't think we got to the point where we needed to do the urlencoded, so that explains why we probably didn't do it.

Thanks for your help on this, and glad you are getting use out of this. I'll review this and try to merge Friday (today, depending on where you are in the world).

**Comment by ahuggins** [comment]
Created a release for others to use: https://github.com/cogitools/hapi/releases

**Comment by igorsantos07** [comment]
Curious you didn't need the urlencode part!

Will keep pushing PRs around here. It's good to see an island of
maintenance in a sea of forgotten code :D

**Comment by ahuggins** [comment]
Did I mess up the merge? I intended to include it.

**Comment by igorsantos07** [comment]
No, I meant you didn't need urlencode when you initiated this fork. I needed that to authenticate, go wonder 🤷‍♂️ 

Anyways, could you open up issues on this repo, @ahuggins?
It's something a bit different from the original anyway, and I wanted to keep track of some things that need improvement but I'm afraid of tackling right now. It's a good way to discuss further changes.

**Comment by ahuggins** [comment]
I added Issues to the repo, I think, if you can not see them just reply again and let me know. I’m not sure if I have to make them public or not.

**Pull request merged**
